# Generated by Django 4.2.7 on 2025-11-19 02:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('job_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Preferred job types (internship, job, fellowship)', size=None)),
                ('sectors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Preferred sectors', size=None)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('max_distance_miles', models.IntegerField(blank=True, help_text='Maximum distance in miles', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='running', max_length=50)),
                ('sites_scraped', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), default=list, size=None)),
                ('jobs_found', models.IntegerField(default=0)),
                ('jobs_added', models.IntegerField(default=0)),
                ('jobs_updated', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('job_type', models.CharField(choices=[('internship', 'Internship'), ('job', 'Full-Time Job'), ('fellowship', 'Fellowship')], default='job', max_length=50)),
                ('organization', models.CharField(max_length=500)),
                ('company_link', models.URLField(blank=True, max_length=500, null=True)),
                ('company_logo', models.URLField(blank=True, max_length=500, null=True)),
                ('locations', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('work_format', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('zip_codes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, size=None)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('technical_skills', models.JSONField(blank=True, default=dict)),
                ('soft_skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('sectors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('apply_link', models.URLField(max_length=500)),
                ('source_domain', models.CharField(blank=True, max_length=200)),
                ('closed', models.BooleanField(default=False)),
                ('sponsorship_required', models.BooleanField(default=False)),
                ('posting_date', models.CharField(blank=True, max_length=100)),
                ('date_scraped', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_scraped'],
                'indexes': [models.Index(fields=['job_type', 'closed'], name='scraper_job_job_typ_3322d2_idx'), models.Index(fields=['organization'], name='scraper_job_organiz_1b8f14_idx'), models.Index(fields=['date_scraped'], name='scraper_job_date_sc_5541c9_idx'), models.Index(fields=['latitude', 'longitude'], name='scraper_job_latitud_1951b2_idx')],
            },
        ),
    ]
